# Generated by Django 2.0.7 on 2018-08-03 16:31

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20180803_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='UssdRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=140)),
                ('mobile', models.CharField(max_length=15)),
                ('complaint', models.CharField(blank=True,
                                               choices=[('1', 'No complaint'), ('2', 'Product below quality'),
                                                        ('3', 'Product too expensive')], max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway', models.CharField(max_length=10)),
                ('data', jsonfield.fields.JSONField(default={})),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductLine')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ussdrecord',
            unique_together={('session_id', 'gateway')},
        ),
    ]
