# Generated by Django 2.0.7 on 2018-08-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ussdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussdrecord',
            name='complaint',
            field=models.CharField(blank=True, choices=[('1', 'No complaint'), ('2', 'Product below quality'),
                                                        ('3', 'Product too expensive')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ussdrecord',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
