# Generated by Django 2.0.7 on 2018-08-02 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ussdapp', '0002_auto_20180802_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ussdrecord',
            old_name='phone_no',
            new_name='mobile',
        ),
    ]
