# Generated by Django 2.0.7 on 2018-08-02 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ussdapp', '0004_auto_20180802_0708'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ussdrecord',
            unique_together={('session_id', 'gateway')},
        ),
    ]
