# Generated by Django 2.0.7 on 2018-08-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ussdapp', '0006_auto_20180802_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussdrecord',
            name='session_id',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterUniqueTogether(
            name='ussdrecord',
            unique_together={('session_id', 'gateway')},
        ),
    ]
