# Generated by Django 2.0.7 on 2018-07-20 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Manufacturer')),
            ],
        ),
    ]
