# Generated by Django 2.0.7 on 2018-08-06 10:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import product.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('production_date', models.DateField(default=datetime.datetime.now)),
                ('expiry_date', models.DateField(default=datetime.datetime.now)),
                ('batch_number', models.IntegerField(blank=True, default=549639, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Location')),
            ],
            options={
                'verbose_name': 'Batch Number',
                'verbose_name_plural': 'Batch Numbers',
            },
        ),
        migrations.CreateModel(
            name='CodeCollection',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.BigIntegerField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
                ('activation_count', models.IntegerField(default=0)),
                ('batch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Batch')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.CodeCollection')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('is_active', models.BooleanField(default=False)),
                ('code', models.IntegerField(validators=[product.models.validate_code_length])),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Manufacturer')),
            ],
            options={
                'verbose_name': 'Product Line',
                'verbose_name_plural': 'Product Lines',
            },
        ),
        migrations.AddField(
            model_name='productcode',
            name='product_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductLine'),
        ),
        migrations.AddField(
            model_name='batch',
            name='product_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductLine'),
        ),
    ]
