# Generated by Django 2.0.7 on 2018-07-29 22:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 29, 22, 16, 49, 407022), null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Location'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='production_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 29, 22, 16, 49, 406986), null=True),
        ),
    ]
