# Generated by Django 2.0.7 on 2018-07-29 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180729_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 29, 22, 18, 30, 155679), null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='production_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 29, 22, 18, 30, 155643), null=True),
        ),
    ]
