# Generated by Django 2.0.7 on 2018-07-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('batch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Batch')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductLine')),
            ],
        ),
    ]
