# Generated by Django 2.0.7 on 2018-07-29 22:41

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180729_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 29, 22, 41, 29, 279641), null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='production_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 29, 22, 41, 29, 279607), null=True),
        ),
    ]
