# Generated by Django 2.0.7 on 2018-07-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productline',
            old_name='name',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='production_date',
            field=models.DateTimeField(),
        ),
    ]
