# Generated by Django 2.0.7 on 2018-07-29 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180729_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 29, 22, 42, 9, 879931), null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='production_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 29, 22, 42, 9, 879897), null=True),
        ),
    ]
