# Generated by Django 2.0.7 on 2018-07-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180720_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productline',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
