# Generated by Django 2.0.7 on 2018-08-03 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0004_auto_20180803_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=44243, null=True),
        ),
        migrations.AlterField(
            model_name='codecollection',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='accounts.Profile'),
        ),
    ]
