# Generated by Django 2.0.7 on 2018-07-29 22:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_auto_20180729_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_line',
        ),
        migrations.AlterField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 29, 22, 48, 34, 127706), null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='production_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 29, 22, 48, 34, 127665), null=True),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='productcode',
            name='batch_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Batch'),
        ),
        migrations.AddField(
            model_name='productcode',
            name='generated_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcode',
            name='product_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductLine'),
        ),
    ]
