# Generated by Django 2.0.7 on 2018-07-21 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180721_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Manufacturer'),
        ),
    ]
