# Generated by Django 2.0.7 on 2018-07-25 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20180721_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
