# Generated by Django 2.0.7 on 2018-08-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20180806_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=182481, null=True),
        ),
        migrations.AlterField(
            model_name='codecollection',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
