# Generated by Django 2.0.7 on 2018-08-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0009_auto_20180803_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=301453, null=True),
        ),
        migrations.AlterField(
            model_name='codecollection',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
