# Generated by Django 2.0.7 on 2018-08-03 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0008_auto_20180803_2124'),
        ('product', '0010_auto_20180803_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codecollection',
            name='generated_by',
        ),
        migrations.AddField(
            model_name='codecollection',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='accounts.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=520819, null=True),
        ),
    ]
