# Generated by Django 2.0.7 on 2018-08-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0010_auto_20180806_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=615283, null=True),
        ),
        migrations.AlterField(
            model_name='productline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
