# Generated by Django 2.0.7 on 2018-07-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20180729_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
