# Generated by Django 2.0.7 on 2018-08-06 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0011_auto_20180806_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='codecollection',
            name='product_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='product.ProductLine'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=577308, null=True),
        ),
    ]
