# Generated by Django 2.0.7 on 2018-07-30 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20180730_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=828608, null=True, unique=True),
        ),
    ]
