# Generated by Django 2.0.7 on 2018-07-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20180730_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='code',
            field=models.CharField(default=1, max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=420201, null=True, unique=True),
        ),
    ]
