# Generated by Django 2.0.7 on 2018-07-31 16:36

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20180731_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=501321, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productline',
            name='code',
            field=models.CharField(max_length=2, unique=True, validators=[product.models.validate_code_length]),
        ),
    ]
