# Generated by Django 2.0.7 on 2018-07-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20180731_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productline',
            name='code',
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=23144, null=True, unique=True),
        ),
    ]
