# Generated by Django 2.0.7 on 2018-07-31 16:39

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20180731_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='code',
            field=models.CharField(default=1, max_length=2, unique=True, validators=[product.models.validate_code_length]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=499983, null=True, unique=True),
        ),
    ]
