# Generated by Django 2.0.7 on 2018-07-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20180731_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=329091, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='product_code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
