# Generated by Django 2.0.7 on 2018-07-31 16:57

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20180731_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=242258, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='product_code',
            field=models.IntegerField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='productline',
            name='code',
            field=models.IntegerField(max_length=2, validators=[product.models.validate_code_length]),
        ),
    ]
