# Generated by Django 2.0.7 on 2018-07-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20180731_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=696963, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='product_code',
            field=models.IntegerField(unique=True),
        ),
    ]
