# Generated by Django 2.0.7 on 2018-07-31 16:58

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20180731_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=590563, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productline',
            name='code',
            field=models.IntegerField(validators=[product.models.validate_code_length]),
        ),
    ]
