# Generated by Django 2.0.7 on 2018-07-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20180731_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=923356, null=True, unique=True),
        ),
    ]
