# Generated by Django 2.0.7 on 2018-07-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20180731_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productline',
            options={'verbose_name': 'Product Line', 'verbose_name_plural': 'Product Lines'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=762866, null=True),
        ),
    ]
