# Generated by Django 2.0.7 on 2018-08-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0026_auto_20180731_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=575674, null=True),
        ),
    ]
