# Generated by Django 2.0.7 on 2018-08-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0028_auto_20180802_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=190770, null=True),
        ),
    ]
