# Generated by Django 2.0.7 on 2018-08-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0029_auto_20180802_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=407633, null=True),
        ),
    ]
