# Generated by Django 2.0.7 on 2018-08-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0030_auto_20180802_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=65926, null=True),
        ),
    ]
