# Generated by Django 2.0.7 on 2018-08-02 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0036_auto_20180802_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=594601, null=True),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='product.CodeCollection'),
        ),
    ]
