# Generated by Django 2.0.7 on 2018-08-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0037_auto_20180802_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcode',
            name='collection',
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=741880, null=True),
        ),
    ]
