# Generated by Django 2.0.7 on 2018-08-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0040_auto_20180802_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(blank=True, default=530538, null=True),
        ),
    ]
