# Generated by Django 2.0.7 on 2018-07-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
