# Generated by Django 2.0.7 on 2018-08-03 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_remove_manufacturer_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='accounts.Industry'),
        ),
    ]
