# Generated by Django 2.0.7 on 2018-08-03 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_manufacturer_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='category',
            new_name='industry',
        ),
    ]
