# Generated by Django 2.0.7 on 2018-07-31 16:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180731_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='code',
            field=models.IntegerField(unique=True, validators=[accounts.models.validate_code_length]),
        ),
    ]
