# Generated by Django 2.0.7 on 2018-08-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180803_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
