# Generated by Django 2.0.7 on 2018-08-03 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_auto_20180803_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Manufacturer Position', 'verbose_name_plural': 'Manufacturer Positions'},
        ),
    ]
