# Generated by Django 2.0.7 on 2018-08-03 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_auto_20180803_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
    ]
